# Develop override settings

url: http://localhost:4000

theme: minimal-mistakes-jekyll

analytics:
  provider: false

comments:
  disqus:
    shortname            : "pme123-dev"

sass:
  style: expanded